# Generated by Django 4.2.3 on 2023-09-28 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guardian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=64)),
                ('date_of_birth', models.DateField()),
                ('sex', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10)),
                ('delayed_milestones', models.CharField(choices=[('Cannot Sit', 'Cannot Sit'), ('Cannot Walk', 'Cannot Walk'), ('Cannot Move Head', 'Cannot Move Head'), ('Cannot Use Hands', 'Cannot Use Hands'), ('Other', 'Other')], max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='guardian.guardian')),
            ],
        ),
    ]
