# Generated by Django 4.2.5 on 2023-09-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0003_communityhealthvolunteer_delete_healthworker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityhealthvolunteer',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
