# Generated by Django 4.2.5 on 2023-09-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0004_alter_communityhealthvolunteer_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityhealthvolunteer',
            name='first_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='communityhealthvolunteer',
            name='last_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=32),
        ),
    ]
