# Generated by Django 4.2.5 on 2023-09-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0005_alter_communityhealthvolunteer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityhealthvolunteer',
            name='password',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=32),
        ),
    ]
