# Generated by Django 4.2.3 on 2023-09-28 12:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('childregistration', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelfCareActivity',
            fields=[
                ('basetime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracking.basetime')),
                ('bathing', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('using_toilet', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('dressing', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('eating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('total', models.PositiveIntegerField(default=0)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='childregistration.childregistration')),
            ],
            options={
                'abstract': False,
            },
            bases=('tracking.basetime', models.Model),
        ),
        migrations.CreateModel(
            name='ParticipationInSocialLife',
            fields=[
                ('basetime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracking.basetime')),
                ('school', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('friends', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('religious_places', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('leisure', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('total', models.PositiveIntegerField(default=0)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='childregistration.childregistration')),
            ],
            options={
                'abstract': False,
            },
            bases=('tracking.basetime', models.Model),
        ),
        migrations.CreateModel(
            name='MovingAbility',
            fields=[
                ('basetime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracking.basetime')),
                ('inside_the_house', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('around_the_house', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('in_the_block', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('far_outside', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('total', models.PositiveIntegerField(default=0)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='childregistration.childregistration')),
            ],
            options={
                'abstract': False,
            },
            bases=('tracking.basetime', models.Model),
        ),
        migrations.CreateModel(
            name='DailyLiving',
            fields=[
                ('basetime_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracking.basetime')),
                ('chore_activities', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('cooking', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('washing', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('playing', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('total', models.PositiveIntegerField(default=0)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='childregistration.childregistration')),
            ],
            options={
                'abstract': False,
            },
            bases=('tracking.basetime', models.Model),
        ),
    ]
